sonar.organization=aripalo
sonar.projectKey=aripalo_rehype-external-link-title
sonar.projectName=rehype-external-link-title

sonar.sources=src
sonar.tests=test
sonar.test.inclusions=test/**/*.test.ts

sonar.exclusions=**/dist/**,**/node_modules/**,**/coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
